=== sambasquash/sambasquash/xml/utenti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.localhost"
    xmlns="http://www.localhost"
    elementFormDefault="qualified" >
    
    <xsd:element name="utenti" type="TipoUtenti" />
    <!-- definizione Tutenti -->
        <xsd:complexType name="TipoUtenti">
            <xsd:sequence maxOccurs="unbounded">
                <xsd:element name="utente" type="TipoUtente" />
            </xsd:sequence>
        </xsd:complexType>
        <!-- definizione Tutente -->
        <xsd:complexType name="TipoUtente">
            <xsd:sequence>
                <xsd:element name="nome" type="xsd:string" />
                <xsd:element name="username" type="xsd:string" />
                <xsd:element name="email" type="xsd:string" />
                <xsd:element name="password" type="xsd:string" />
                <xsd:element name="tipo" type="Ttipo" />
            </xsd:sequence>
        </xsd:complexType>
        <!-- definizione Ttipo -->
        <xsd:simpleType name="Ttipo">
            <xsd:restriction base="xsd:string">
                <xsd:enumeration value="admin"/>
                <xsd:enumeration value="user"/>
            </xsd:restriction>
        </xsd:simpleType>
</xsd:schema>

=== sambasquash/sambasquash/xml/utenti.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="utenti.xsl"?>
<utenti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="utenti.xsd">
    <utente>
        <nome>Bogdan</nome>
        <username>admin</username>
        <email>bogdann@hotmail.it</email>
        <password>admin</password>
        <tipo>admin</tipo>
    </utente>
    <utente>
        <nome>Simone</nome>
        <username>scampagn</username>
        <email>fransim@hotmail.it</email>
        <password>scampagn</password>
        <tipo>user</tipo>
    </utente>
</utenti>
